apiVersion: v1
kind: Service
metadata:
  name: sto-core
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sto-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sto-core.selectorLabels" . | nindent 4 }}
